-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here

-- vim.cmd([[
--   autocmd TermOpen * startinsert
-- ]])

-- function OpenDiagnosticIfNoFloat()
-- 	for _, winid in pairs(vim.api.nvim_tabpage_list_wins(0)) do
-- 		if vim.api.nvim_win_get_config(winid).zindex then
-- 			return
-- 		end
-- 	end
-- 	-- THIS IS FOR BUILTIN LSP
-- 	vim.diagnostic.open_float(nil, {
-- 		scope = "cursor",
-- 		focusable = false,
-- 		close_events = {
-- 			"CursorMoved",
-- 			"CursorMovedI",
-- 			"BufHidden",
-- 			"InsertCharPre",
-- 			"WinLeave",
-- 		},
-- 	})
-- end
--
-- vim.api.nvim_create_augroup("lsp_diagnostics_hold", { clear = true })
-- vim.api.nvim_create_autocmd({ "CursorHold" }, {
-- 	pattern = "*",
-- 	callback = OpenDiagnosticIfNoFloat,
-- 	group = "lsp_diagnostics_hold",
-- })
