#!/bin/bash
 
# Start pulseaudio
# start-pulseaudio-x11

killall -9 picom sxhkd ksuperkey batsignal
# killall -9 picom sxhkd 

bash "$HOME"/.config/bspwm/autostart.sh &

# VLC fullscreen controls fix
bspc rule --add vlc:vlc border=off layer=above
bspc rule -a Zathura state=tiled

bspc config border_width	2
bspc config window_gap		0

bspc config split_ratio		0.62
bspc config focus_follows_pointer	true
bspc config pointer_modifier	mod1

bspc config automatic_scheme	spiral
bspc config pointer_motion_interval 6

bash "$HOME"/.config/bspwm/monitor/bspc_monitor.sh &
# workspaces() {
# 	name=1
#         for monitor in $(bspc query -M); do
# 		# bspc monitor "${monitor}" -n "$name" -d '' '' '' '' '' '' ''
# 		bspc monitor "${monitor}" -n "$name" -d '' '' '' ''
# 		let name++
# 	done
# }
bspc monitor "eDP-1" -d '' '' '' ''
# workspaces

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

bspc config border_width         3
bspc config window_gap           10
bspc config split_ratio          0.50

bash "$HOME"/.config/bspwm/polybar/launch.sh &

bspc config focused_border_color "#7bc5e4"
bspc config normal_border_color "#32344a"
bspc config active_border_color "#444b6a"

bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

# Wallpaper
# /home/brad/.local/bin/kittybg random
bash "$HOME"/.config/bspwm/.fehbg &

# Start compositor
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
picom --config "$HOME"/.config/bspwm/picom.conf &

dunstify -i window_list "Successfully restarted BSPWM"
