torrent_client_cmd = 'bash -c "curl {torrent} > ~/torrents/{title}.torrent"'
default_category = 'AllCategories'
default_filter = 'NoFilter'
default_sort = 'Date'
default_theme = 'Default'
default_search = ''
