default_category = "AllCategories"
default_filter = "NoFilter"
default_sort = "Date"
default_search = ""
theme = "Dracula"
source = "NyaaHtml"
download_client = "qBittorrent"
date_format = "%Y-%m-%d %H:%M"
base_url = "https://nyaa.si/"
timeout = 30

[client.command]
cmd = "curl \"{torrent}\" > ~/{file}"
shell_cmd = "sh -c"

[client.qBittorrent]
base_url = "http://localhost:8080"
username = "admin"
password = "adminadmin"
tags = [
    "Ttesting",
    "testing, 2",
]

[client.transmission]
base_url = "http://localhost:9091/transmission/rpc"
username = "user"
password = "pass"
labels = ["nyaa"]
paused = true
peer_limit = 12
download_dir = "/home/brad/Downloads/trans/"
bandwidth_priority = 1

[client.default_app]

[client.download]
save_dir = "~/Downloads/test"
