alias kittyc="$EDITOR $HOME/.config/kitty/kitty.conf"
alias hyprc="$EDITOR $HOME/.config/hypr/hyprland.conf"
alias hyperc="hyprc"
alias wayc="$EDITOR $HOME/.config/waybar/config"
alias wofic="$EDITOR $HOME/.config/wofi"
alias ss="screenshot"
